_wandb:
    value:
        cli_version: 0.26.1
        e:
            muz481u6wpf15yxo34vg0u5lyyja9zbw:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    macModel: Mac14,2
                    memoryGb: 8
                    name: Apple M2
                    pcpuCores: 4
                    ramTotalBytes: "8589934592"
                    swapTotalBytes: "4294967296"
                codePath: models/train_v2.py
                codePathLocal: train_v2.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "384461430784"
                email: atharvaabhyankar4@gmail.com
                executable: /Users/atharva/miniconda3/envs/fraud-mlops/bin/python
                git:
                    commit: 54aac3e075d85c63df315f0868cbe9a862889607
                    remote: https://dagshub.com/aniketdesh004/Fraud_detection.git
                host: Atharvas-MacBook-Air-3.local
                memory:
                    total: "8589934592"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/atharva/Documents/Fraud_detection/models/train_v2.py
                python: CPython 3.9.25
                root: /Users/atharva/Documents/Fraud_detection/models
                startedAt: "2026-05-05T05:56:30.243981Z"
                writerId: muz481u6wpf15yxo34vg0u5lyyja9zbw
        m: []
        python_version: 3.9.25
        t:
            "1":
                - 5
                - 6
                - 53
            "2":
                - 5
                - 6
                - 53
            "3":
                - 13
            "4": 3.9.25
            "5": 0.26.1
            "12": 0.26.1
            "13": darwin-arm64
