name: Fraud API CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Grab the code from GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Python & DVC
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install DVC
        run: pip install dvc

      # 3. Authenticate with DagsHub and pull the model
      - name: Pull Data from DagsHub via DVC
        env:
          # This pulls the hidden secrets into the cloud computer's memory
          DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # 1. Tell DVC to use basic authentication
          dvc remote modify origin --local auth basic
          
          # 2. Inject the username and token into DVC's local configuration
          dvc remote modify origin --local user $DAGSHUB_USERNAME
          dvc remote modify origin --local password $DAGSHUB_TOKEN
          
          # 3. Now that it is authenticated, pull the massive CSV files!
          dvc pull

      # 4. Build the Docker Container to ensure no code is broken
      - name: Build Docker Image
        run: docker build -t fraud-api:ci-test .
